import { Inter, Lato } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Dashboard/Navbar";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'], // Elige los pesos que necesites
  variable: '--font-lato',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${lato.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}